package game.domain.items.model

object ItemAttributesConstants {
    const val GEAR = "gear"
    const val SURVIVOR = "srv"
    const val WEAPON = "weap"
    const val CARRY = "carry"
    const val EQUIP = "equip"
    const val INFECTED_KILL_XP = "infected_kill_xp"
    const val SURVIVOR_KILL_XP = "survivor_kill_xp"
    const val HUMAN_KILL_XP = "human_kill_xp"
    const val CLS = "cls"
    const val TYPE = "type"
    const val AMMO = "ammo"
    const val ANIM = "anim"
    const val SND = "snd"
    const val SWING = "swing"
    const val PROJ = "proj"
    const val RLDANIM = "rldanim"
    const val EXP = "exp"
    const val NOISE = "noise"
    const val RATE = "rate"
    const val RLDTIME = "rldtime"
    const val AMMO_COST = "ammo_cost"
    const val INJURY_CHANCE = "injuryChance"
    const val RNG_MIN_EFF = "rng_min_eff"
    const val REVERSE_RATE = "rate"
    const val REVERSE_RLDTIME = "rldtime"
}
